spring:

  application:
    name: apigateway

  rabbitmq:
    username: user
    password: password

  bus:
    enabled: true
    refresh:
      enabled: true

  cloud:
    bootstrap:
      enabled: true

    gateway:
      server:
        webflux:

#          discovery:
#            locator:
#              enabled: true
#              lower-case-service-id: true

          routes:
            - id: users-status-check
              uri: lb://users-ws
              predicates:
                - Path=/users-ws/users/status/check
                - Method=GET
                - Header=Authorization, Bearer (.*)
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter

            - id: users-actuator-refresh
              uri: lb://users-ws
              predicates:
                - Path=/users-ws/actuator/**
                - Method=GET, POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

            - id: users-h2-console
              uri: lb://users-ws
              predicates:
                - Path=/users-ws/h2-console
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

            - id: users-create
              uri: lb://users-ws
              predicates:
                - Path=/users-ws/users
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

            - id: users-login
              uri: lb://users-ws
              predicates:
                - Path=/users-ws/users/login
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

            - id: users-get-update-delete
              uri: lb://users-ws
              predicates:
                - Path=/users-ws/users/**
                - Method=GET, PUT, DELETE
                - Header=Authorization, Bearer (.*)
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter

            - id: users-ws-actuator
              uri: lb://users-ws
              predicates:
                - Path=/users-ws/actuator/**
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/users-ws/(?<segment>.*), /$\{segment}

#            - id: albums-status-check
#              uri: lb://albums-ws
#              predicates:
#                - Path=/albums-ws/albums/status/check
#                - Method=GET
#              filters:
#                - RemoveRequestHeader=Cookie
#                - RewritePath=/albums-ws/(?<segment>.*), /$\{segment}



eureka:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

  client:
    eureka-service-url-poll-interval-seconds: 60

server:
  port: 8088

api:
  registration:
    url: "/users-ws/users"
  login:
    url: "/users-ws/users/login"
  h2-console:
    url: "/users-ws/h2-console"

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false